# databases:
#   - name: blitzapp-db
#     plan: free

services:
  - type: web
    name: refilist
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: blitzapp-db
      #     property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
